version: "3.9"

services:
  api:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/hadiths_api:/usr/src/app/hadiths_api
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12.13-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hadiths_api_dev
    restart: unless-stopped
  web:
    build: ./frontend
    command: npm start
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./frontend/prophet/:/app

volumes:
  postgres_data:
