# Generated by Django 4.1.4 on 2022-12-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="sequence",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="hadith",
            name="sequence",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
