# Generated by Django 4.1.4 on 2022-12-31 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_remove_book_description_book_about_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hadith",
            name="chapter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.chapter",
            ),
            preserve_default=False,
        ),
    ]
