# Generated by Django 4.1.4 on 2022-12-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_hadith_chapter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hadith",
            name="number",
        ),
    ]
