# Generated by Django 4.1.4 on 2022-12-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_remove_hadith_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hadith",
            name="sequence",
            field=models.IntegerField(default=0),
        ),
    ]
