# Generated by Django 4.1.4 on 2023-01-01 23:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_alter_hadith_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="about_book",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
