# Generated by Django 4.1.4 on 2023-01-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_alter_book_about_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="sequence",
            field=models.IntegerField(default=0),
        ),
    ]
