# Generated by Django 4.1.4 on 2023-01-02 02:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0010_alter_book_additional_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="additional_notes",
            field=ckeditor.fields.RichTextField(blank=True, default="", null=True),
        ),
    ]
