# Generated by Django 4.1.4 on 2023-01-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0013_vocablurayindex_vocabulary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocabulary",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book.vocablurayindex"
            ),
        ),
    ]
