# Generated by Django 4.1.4 on 2023-01-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0014_alter_vocabulary_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hadith",
            name="text",
            field=models.TextField(),
        ),
    ]
