# Generated by Django 4.1.5 on 2023-01-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0015_alter_hadith_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vocabulary",
            name="description",
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="des",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="term",
            field=models.CharField(max_length=225),
        ),
        migrations.DeleteModel(
            name="VocablurayIndex",
        ),
    ]
